[[Musl]]
arch = "x86_64"
git-tree-sha1 = "1c4d75e7512e272f3dd906e817acb58cb74867e8"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "af069c12d403b3e0b64c59ec66dc2d06c5c885dc6452f9a6dc26ae62c38b7d90"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "2cf2bb4933515caea39375a5726a1cd02d3930da"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "afbb10ad735f99a3f88bedba5bcaab75f954e3bd15be96f76eecfbef2a09c4d6"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-v1.1.25-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "8f145598de39bade4365fc38e4f2ee1190d7c2b5"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "adf76b5af73c813775c7f738f1a417a1443a9a2a58e8700cf338d3e028e92142"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f52fa239379254f8a2fdd206fd7d7befafac04bc"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "d9432b8f4022f1726dfe54f8cc34578207b6cc362476e71eb8c78e6061f0d2f5"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "caf3604462d58532b56a338d6c48ab8496bf51fe"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "b4e8b2412a3d2a9f001b8ffec04259613d5bf265ede6cf18e992e8289145a5d4"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "b07555e38b3c4a872d2ae123b2a0d5f9afa68f72"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "b6c7440c0a8b31241fc29974634468994e8a9a3e8932e6ba82f06dabc5e3a570"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-build_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "66a0e14390df22b658b0746a2eebf3ba38a8dba9"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "f592d22742b015f8249b16f3a6353508ce7d3b7bccce1135cc213c9db2672f96"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-build_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "23f91524a71a05ac32410a254b19b40f2d6a4a44"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "58f74a40911fa7f755a222c94ceb6499d25af3fe1bf18ddf01335d623f790411"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-build_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e296f30440eaa461f10809d316ae9449691a54e"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "02eb2d640b97df82ff93450a9b41d907e9c7e5169dc25c78cdbd9cc0351020b8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-build_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ddbaddf6af261d4698c8b6ee6d4a3d6f30380351"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "fa53ded8efc4bf7c7b9428378998aafe7559afcb9883d75eba761a5b00d62df1"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-build_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3421ca86726ab8d7aa2be7aa5828c7152f8134c5"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "d9e2715ca4f0b34b8c3d0db2bdebed1a1640f571a24ade2b6ca8e95da20cb3e8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-extract_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "192f14c9c4042963202f9bc7161343e18fc5680a"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "80e9649d7bc68dd0ef59281e73eb7d62d0d8a26740c67d544f81b7f775d02639"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-extract_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "91071d07860ce4c21e5b24fd999594aab9fe5c8d"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "039e1845743f2a2983564866ad9c5790e0559e74a4523976a52944a08559acc3"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-extract_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d652b70c63e6b3e2cce08199d409142208cbb02f"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "fb631c237f5736e5d07ab4c1250e8021a8db525029a47afe24fd2fedd070182e"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-extract_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee7cd75c8d0862e8d14167ec2cae792e09659be3"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "0b7cecd77d43b2209d44df90ef20d0aedf7d4cb4a3fa0266c08e5e4f5428c4bc"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25-GCC/Musl-extract_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"
