[[Musl]]
arch = "x86_64"
git-tree-sha1 = "da99afe11a7fa294b091eb2f306da8fb1cb5628b"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "4419d98fe8e48a70a6ee6a67fe27643d15f98e7dceb9b4b547cb3c88c9bb6e38"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "24606febc7fe84aed998531c1545eb8d0ab63b63"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "fdab80aa805e41c62da273732afba394225c2ade94942808b31cd761047decf8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "d2055eb72cc13a12c6e0499e170a1ccbc8373f9e"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "ea77090964838d5f8ece01e479ae4d590d8ee56f18251aedc71e0fccc23e9d4e"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c86fdac09b876de9c68d14d7563e186e4f0c88b6"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "b72dd9f91fd9aa8e627a7195e54a75b42fa9c9db0aa9f18ab15f3e656b8e42dc"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63148deab529363e4fd2bbbe4e6b94aed8aeedbd"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "441651dd02c65659eaa65dab2a1b375234e00e8e7b81d94726669a452dd32f00"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "e2865027bed2616dc9622d869419fea048711be0"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "8b765e5c88823d756cb745f6263d18b720a56e03bba9c49c7a501803c5a273c0"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "406ec84a1978c32b1f5a372f080adb608516164e"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "1936907d206cfca7c8c1355a45cf8a90f1b329a489896e2cbe2c324c14826cb7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "e29c87bd302bc7790214bfae980396fe2339b289"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "65be6133f10a2a4d667f88d9ee3b55aee79aaa2fcc7e52386e3d3e2ecfe1bf22"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22ef845c3062aa8ce9419dad4393d67bc76e299b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "38dac91a2e8c9dd0bce041060683ee76267ab3fb759e9fee071a28e4b25ca6e0"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9285cb417791c4fc0048a0185079f19a2071dfd"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "380eec66271d5db971a43c4a0d195b9f49a70d3543dba02c7455e8c23c457be0"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5740d3037fd8f8024c04d6e30b7885bb29ec0c3b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "727152e10b72b4ab1c7cfe9f2d4f6b0a81fb223dce6e8ad410ef03db6f51d67a"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "bbf47c68c7ef33b73eed66249824d42b4a5407e0"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "0e2ced6d44c7f4eb665ad6efb027103527d13dc3d700e028be2ac62b24578612"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "0ce3b0e8f22107106dfbb2a97122df00f59467da"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "d5c2b8d2897a704b98b8f73ff0cf24d5f98cc66a71d13cfa50ca832438f16539"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8d6223639572f3a0e85edf322ae13dccbdd76e3"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "ab835d1104b70c05f66fdaa0609585b6ea13636b4a19abd541bd623653602a94"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c81d510e50d2b49d7dfe915962cd488959a56dc"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "684c91b3280aa5a84ca768aeb965e10b5ad491b40324cac241078111e4b7cd5c"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"
