[[Musl]]
arch = "x86_64"
git-tree-sha1 = "3303ab27c550e269c1a597fb7502f0f12519d164"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "b0a1970614af6d893ab401d0585da0dbc686324052d99960a19f5d15b81e7522"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-v1.1.28-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "bfd2afe5b7c5ee152909b1efad4ebec48ce7bee4"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "c05df4ddbf62c2784cf359c8ce5720a5b4c39c4cbe78e538943c1ac10e9ec31b"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-v1.1.28-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "e04ed249a2a90904d24f39ffb28440ac2ae69570"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "2b8ce61e98107f601eca46103be94853b76da4f5903969a6b39ab61f54cab833"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-v1.1.28-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "979b1878fc0aabf9d109cd055fdd980ad74114ad"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "3b0ee8e60d8b19b163b7c40a089bf18712588428d069079d4efad0d12c23bbc7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-v1.1.28-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "548d61d2e052807512de8305479b0d78b465a0a9"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "04dbfa151ed1626b4c6b486dfde117f3c493ae7ecc7b20fd3ed98cae47f175a6"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-v1.1.28-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "8de0bd41646da8c1af0132d4667920fa09141fe6"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "ca045673956e3c328bf76e924130943d33d70fa909954bdff4e8ba67224be4b2"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-build_log-v1.1.28-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "49f49d10a32b0cdd08113d2f3ffb4e4a424d3bc9"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "6036cb62caf24c7c56244dd00d0fc22ee87375591925944c898ad4182b20bce8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-build_log-v1.1.28-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "9592113e67ecb93a34066d068086dacda1469560"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "ef37d6c53e47550004293058a74be625d8fec8a143c69ae1a7e28c84c5b2ea56"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-build_log-v1.1.28-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0eb3da6775e6aedd758da6cdf92c7a4a2fcf51b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "6f14520f53b8c31a259a9193a5298072d27d40b325682340bb5c24d74e7721dd"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-build_log-v1.1.28-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8bfc1778a7089d5149a6202f885780fa79b5f7f8"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "42b16d4979a80ac7612c0ab86f08d32965f4b3b701f0aea8a4d185f9331abf14"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-build_log-v1.1.28-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "053dff8469f01d499780bb4625660a96b7f71acf"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "b4e809b4c83fdf0ce32cd6c2c2da95dafc230443c509efba15d1008f9a09001c"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-extract_log-v1.1.28-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "93850cb2050dff76f27f7d19da11836e8d0fe510"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "843648f7caf5d1d3e1ce2e79b8780f9d7e59dba8154a36da0887d6afefd32fe5"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-extract_log-v1.1.28-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "965fa95675a35fdde06b6063fc8b01a360cd3055"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "8e1f01a492a33879e316adcdef19905e3368ea4214197fad505e7ab31717c46d"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-extract_log-v1.1.28-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89c7436c975841ecfc785106659c88c88da2c1bc"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "3a560df26e7686115bf87fb9c8a06c5174062f7f4ec202de1a3ab0a0b2ab2db8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-extract_log-v1.1.28-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6f830346b2b0fecb34beb4d5888130b0e69f038"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "f859c25609c33cf0ee4a7be9ca8af2e8fe9d1a146eb35cb54352f8fa02c795d7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.28-GCC/Musl-extract_log-v1.1.28-armv7l-linux-musleabihf.tar.gz"
