[[Musl]]
arch = "x86_64"
git-tree-sha1 = "12af206e258853b929e795c5c016ce33d58f502b"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "002c464282beac1614127b7d588b9795fba62e857187c0d2bc058d98f6c00890"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-v1.2.5-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "1561eeda01eea53fbe435f4d996531e8bb87f750"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "e6afa633ae0865ffd7447d8aa25739e7ee2b04b888e09bc8a18453e816f72a98"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-v1.2.5-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "ececeb44a385f1a933bfcbc610f8cb142643d563"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "155d1de99fdc8135d4cf9601a16d96945ccb451bec9dc337e873ff9998f609ea"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-v1.2.5-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "377852102c7427ddc5089d76f802991576118f21"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "8bcba72296d4778f7b6a4a9e0c6d016f0e581124cb3a300f406b208b6cb530f7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-v1.2.5-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4bb9609bbb2aa8749e7f399394da101c68ed1fd"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "83346e7e530351d5cca9282d9829581723a009c212380f36424e986e31a52f44"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-v1.2.5-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "267cba40cbd3f9ad09aab58e6cac1d1ddad347a1"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "f7b7d894683a4a7488fa6d78288297d371b3dc0f359471152a02f9ed072bd9cb"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-build_log-v1.2.5-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "030cdb9462fa6276e8a683d2b90b538d78e844fa"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "23a451ac1290081ee5c2b516aef05e3dfd4c31ee9389d65252c1c86f978120cb"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-build_log-v1.2.5-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "d30c54a62ebe1d9b7f1e7317c8fe462f0a7d8741"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "c99cf3e45487ab50e69fadaa353f90de5da3950b3b9f79026e528ba00679efbc"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-build_log-v1.2.5-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cfff125b788160dc26226442da7830bacfe085cd"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "410505710726c0e5a5e3f970a7fc05f56932e84de7c7b9c7769215d51d5bcacf"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-build_log-v1.2.5-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "115ee9f4d1779617c3b23062bce1bee4bf53d94b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "3c479a843da48c616007d4c1c8b7b6c494ec9df8cd215fd57a63235ab9942f13"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-build_log-v1.2.5-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2e24a7a734059a6ef6b610f4b3ff69e5be57b8a1"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "a0fd85fdf71ed1ae2df05307236c58d6f9bef224cf0fe1272023a5ec89637429"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-extract_log-v1.2.5-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "d26b53e2d3b444485ddddbb628040ca860f413b0"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "3b7176daaf84c8fc8e728bd9c53f8c54a09895a44fd91a2b86f9dade484b76d8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-extract_log-v1.2.5-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "85460110208c6c19fb251547864bbaf9a54adc02"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "3b9452a24af258315b11de6cc8fd3dcc3ca99814a9be20b50cc5c8d1f310c86b"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-extract_log-v1.2.5-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22e4e72439e64d1e44b75e422972ed3aaf0bdc34"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "d47f0220a5cbd3298bba4c41cc7b87fb34cc303cc8c5cb9a8c771ed60e13b2b2"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-extract_log-v1.2.5-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cb9daa21b34bf21a32f5f9124a50561d4407be2"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "479227f3bcd353a9be508d70163472d993bcd193bbc98f36516358a20483f7a9"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.5-GCC/Musl-extract_log-v1.2.5-armv7l-linux-musleabihf.tar.gz"
