[[Musl]]
arch = "x86_64"
git-tree-sha1 = "c3731bb4e6ade685344c1bf37e1fd5208fdbd1c2"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "6a3c6e713c92192f5793c22bae4944121ada040d2fd559313e836e6d0139a8f7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-v1.1.31-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "47717d0d1f9be84491c6fa61e37dcd948fddbdfb"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "7745d0b6dd13b68a1b404fbea12f314b0657522542c5fe40f1fd3266204654be"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-v1.1.31-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "5a30a0cec3607b9a9ad8b79ba6caf94548d63373"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "f24f6c8f67e4a9431fafedae7353dc6ede3461c6261fdb88246e1859a020add1"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-v1.1.31-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "401b70fe0e1419333ed257c556fc8d038dd16e07"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "3cbfb7987e10770e84246c02eaca46320e4ebd2b25dca03a20f28aa80e2e65ca"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-v1.1.31-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "272b5dfdb919133141b36aa9814663d9895f7094"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "d8a16f213a1a2617f4db0b7bf5c50984fbbf1cbbebee709d9b595617295e4350"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-v1.1.31-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "1d06320c5ee38963864c9b45e900094a08be5e76"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "abd43aa00989adac387baebc7972a1133ec6cab8f5d1e23bd7e550e598cce856"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-build_log-v1.1.31-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "0feda910ba476e51e4b27ad45be5550350db58da"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "f189d4f75938af912420608c0fd0c9825b1a7ac126f4e800896f1043f1815c22"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-build_log-v1.1.31-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "5df6142d08d13ad169095f5032c472c78f82b813"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "4305ef1a0fa775300d158d26c2e3162929e2ac68af954fbcce921d97dd6d2340"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-build_log-v1.1.31-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba2f2aef081be22e3b1b96a5dbf68fa29c875e08"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "9b15f6ac0eb1725df40d38bfed6ff3ac83860bf2d7d5aa3bab82ebe2e6be05e7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-build_log-v1.1.31-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b3db8c3d33316fdfd3d8c46c6538e6cd7fb6340"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "5ac1f124fad14e7d9c87a8e84538d7cffeb9e9f295d4c276c779ae04e1952cbf"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-build_log-v1.1.31-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4be22f68ebc8113693fb980cb66b549a085c2af4"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "8d808f5b319a1b88f808c7044a8db0e92d181ccb6c6b60582d180451b5517453"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-extract_log-v1.1.31-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "ac84292fadb566215114a82cf1870f159546eed4"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "11dfcb59d01c866278df42fe13b5503c76bb955ad85f419fbc4006353e895d87"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-extract_log-v1.1.31-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d9975f5a84f27391cb24e75c4d49cc673a7a631c"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "f1310db62f5a82e335151c18714273f8cab7577e4a5901e09ec7a3d86089898c"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-extract_log-v1.1.31-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d9a1b6eb76c2483d2b1c5f4b7a3782a4e3406f1"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "51611dff6a7afeeda4aa9dfc3b68c369fc398d04c43c927ea65361fc721174c4"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-extract_log-v1.1.31-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "421a0f94aeebbcd0f60314bb4c007e9787530b0d"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "a66aab2a5bdae85a7291e54b35be9b2e1bc336abce93cf80b7c2fb56936cf796"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.31-GCC/Musl-extract_log-v1.1.31-armv7l-linux-musleabihf.tar.gz"
