[[Musl]]
arch = "x86_64"
git-tree-sha1 = "12af206e258853b929e795c5c016ce33d58f502b"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "b294a6d9eab609e0d97a0cd2431f5796a3b0f936f29c27bfd73bb6b354a02ca6"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "1561eeda01eea53fbe435f4d996531e8bb87f750"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "6458f606715390e20109dc5b5c7101da6bca81afab35f1c676646381f6f7fabc"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "ececeb44a385f1a933bfcbc610f8cb142643d563"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "2f0de2cda037abeadb04b9d28ca12b73d01cb70776498f89fdba29d914193aa0"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "377852102c7427ddc5089d76f802991576118f21"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "d8a610bb4b746837889774d385d23dcf75293d3149e288579c80f56212234f31"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4bb9609bbb2aa8749e7f399394da101c68ed1fd"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "27eb34fdf8186fedb5d944a3a6a5499252f0384cd3e81d6774cfe42d91e0ba64"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "07736324c925d4147d61b858f298e9e557864a52"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "cd1e31179778c9564a2c6d3c780b737106f3dbf8d2cd1cff1d3710e1c45854e3"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "36e53b59ad06cfe9acfed3bf444987887b455bd0"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "d9fde7bc00be1367d661652549aef483350e778068fffc0cb0f5312f6f301d98"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "391c551b36fec0304475ddef78a7d78cbffa3c00"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "97a49ba27d017b8bb194afc674b87d99326c47732fac0ac172deaae06a12a4be"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ada6d51631ed795a313832586be281ce699ad20b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "3409f6ae48e7fa2f0ba6965e3970b6700912326c66e5d56ae4573bcae4438b91"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "581b9dd5d7ad8326878eabaa69a133a1fbd651bd"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "e4e40f288a12dc1f78e13bd25f4ee99e256dcfbf68c35bdce553bfcf30641733"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "72905129848ecae3672247852aa3c49c839c6ed5"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "1756d2209d6eb93aad91dc1c30ae89bcd2e294f8c8e98df7cfa6467e4192bb73"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "443e39d2ee8cc9d6be6bc7a3054c2f6b4f02a1ff"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "22c5b48438f1cc8da34f598e46a979eda33b860e40d0eaf486e6d72baf799c62"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f6b2090c55697ff7eded3f985b704514b76e97fb"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "de95e80a2d027a8f639b1ca22e52909706d995869219d854c09651d3382e8f51"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68e33a1051149ee83ef6567cfc0018d1cb2aa25e"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "cef8e7a0edfabf88d6cdf7f78c58e6e1cfba700763de889315f8ea288c34345c"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5c28f7ad68cf6855e68686462fe13a1321f0a9c"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "9a553da630a1375e6fbd8b7292ae9a60a91f8e6a264b3674045be5fae733ad4f"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"
