[[Musl]]
arch = "x86_64"
git-tree-sha1 = "12af206e258853b929e795c5c016ce33d58f502b"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "f6e0a8180b505c3ab14c6857b72276a3737ccfd56589dba950ce6feac3161f5b"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "1561eeda01eea53fbe435f4d996531e8bb87f750"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "6a2b8f54cbf32be693596b8b188fb93e23d62d60ff8dd618a2e10249237c4482"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "ececeb44a385f1a933bfcbc610f8cb142643d563"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "ce59765042cc9896c97675c9e8fba3a84d3437a97e4dc64fcbfc0dca1e65ede9"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "377852102c7427ddc5089d76f802991576118f21"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "852bbfcc8f0949af7f954422f84eb2c054b3d2aecafbd310e5a00aebef29f0a8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4bb9609bbb2aa8749e7f399394da101c68ed1fd"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "7d64492c4015276bf04ca0ce90415fbf5b658edc3414684e37b8c2f3fac7cd3e"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "520eeca11c3619d8cc26c8612f4e670898f17cad"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "9f70ae0eef047f035b85ebc2df9feca0749ace91db43af84225994b0f72225c7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "290ef15928886b45fa5982878ba5e03e32422f34"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "da86f9c0a1bcaffa531bed087b15bd21c6514e83b721f9ebd92e49f6f84ece0c"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "8a03338518d2f147ef6634c0160f16e1f48fe113"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "fe4dc46a42f66da8fecc9bac2de9a831b73e9437bac32e1aff4a9572e32f9467"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f23d0aaa040c8960cd398dcd7716f18cf061be6"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "00f8e604b3f9d904c10af351b0cc725fe198a3769ff65a242da5a646b55de3d6"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9222cb398dafc498b93de932fb1a5f6f4879a087"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "657e2243ba8787d00a9530348b43a5d0903924bf46ec0acedea566187abbad7b"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-build_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1f815672c3d305f55cfdf87c9898491f2393c8f8"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "043944b2a09127644a4cb33a13cad401d2a0e42802286d8bc5847d203d2e3619"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "e18ba6d3bf8323754346131a61ea590b2418882d"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "5ab7232fe6bc2f265289e6a5d23c45df7711a6bd9126bb20ef05ed8884041988"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b24ce6ac31b969ff9dba05f91eaa365ab492597e"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "739470f2e19ea5a068d066fe1187f60a758205bd4e94b09c150593c5ea3f5f15"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d284f9077a67fd664368370d3047a4399f280f6"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "4d7a36ba1a07f9cadbfe1e6126445a924af1208be9d6bf726ef05bd1f4a01bb1"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b53910c7189c17434f84d9a38cde62407236cb49"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "5c0725b3b77cf9e66b45de13c59639bade3441d5bf91a872823c8ef2349113c9"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6/Musl-extract_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"
