[[Musl]]
arch = "x86_64"
git-tree-sha1 = "302ff9711e6535a8cf0a30bc9167b0b678f599b1"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "516493319598a7d738959f6c0d233d20ab2660386075b777f0bb9d0bd5ad3f03"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "629a1587620e527e41a05aca6e2f5f4bc6e1f553"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "3bdcfa4a9aeed61ef5c962ef56b293958c63da9c890fbb6dbc0846469bddf27d"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-v1.2.6-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "ff5757114ab4596d08920158cd6036bb8601cb70"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "e8ca907a3533fe5d8418796c2a3fd7a777af772ec19e04cb146f36dbb2e372b2"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dacf3ac78db25852f41622d95e63a6d773d8e306"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "36e95e93d8585ae8c2aef7216088849df396edf5449db2ecd8f9dd1185ab1754"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f22e91963d1825d0accaf3ea5f478328f3f5f4e7"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "1ca03e28811266ceef7a7477312c2c2aa5200841e12db7ec03bce1dfe6c72123"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "6d76275b6e0cc885234ce9f1c9d87e4738a3dede"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "035bbcc343415a7f025509be740b2e4859d6c2ac0c28985fbe02e4a38f937fd2"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-build_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "68b385b1bb9a3c414b8e76a47676523a51d5c30f"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "fbb2bb5394518cd2e910f312095fc6fc02262efb13e3b914ce7caf176f302a9e"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-build_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "7e65205427f8a0b55300e20023cdcbe86f43cd97"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "2e6963c9be9fcb4bfcecf1dd8c4f00146b3fe1346847c2499a02df7cc9e786b8"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-build_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "740065448d1e01920a1175b02517904ff2eb0356"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "329663d7909b8477e3d466de8928b58c0d4d1270001b8d58b5767105c860b38b"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-build_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2553e0dd2ddef2cfae4ffc600643a710ac0769c"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "70bcee53da68156c997edae1eab2967bdaed983ae61b98e954b9764ed7792df0"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-build_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f499789096c89030663bbe5729911cd68a7ff95f"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "72ca1137d46cda6e4d8aa7ac64e648ce7fc12d17abfc85ce3207fccef92bd86d"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-extract_log-v1.2.6-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "8dc09ffaf1d8632fec91999628bc8ff60d682162"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "a3b025fc7c9e12c97aab5251769b2febf1278212f5994a9027c275fcff6000ca"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-extract_log-v1.2.6-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2f19fe3eb6e28d9f2ceef5b72e0c86b370033d03"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "d8fae91dfa183eb2b5568d3e156d68038461d78397c90ff5fbdcdf00cdaaa8b9"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-extract_log-v1.2.6-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4c45f19dddbe8a2eaacbbb7039596d6deb4058e9"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "81524034d16cf6a25a9c1f94d00b597527974dff920aa416254e3771dd4e5f62"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-extract_log-v1.2.6-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38860c88fdfaff211314ad48a91e609abda2f3b4"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "3351adf5be37ae913567ec8ec17d2c598a055726160ceb62caf4ba67eb3acceb"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.6-GCCBootstrap-x86_64-linux-gnu/Musl-extract_log-v1.2.6-armv7l-linux-musleabihf.tar.gz"
