[[Musl]]
arch = "x86_64"
git-tree-sha1 = "1c4d75e7512e272f3dd906e817acb58cb74867e8"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "4d0d034ee2777a111e49ed127111b661bcbc1a8893d242445ef9a6d14f8a84c7"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl]]
arch = "i686"
git-tree-sha1 = "2cf2bb4933515caea39375a5726a1cd02d3930da"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "2a3dac55b74b62435dc05d79a682fb17ad46edc4bef35e979d55f634901dbd15"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-i686-linux-musl.tar.gz"
[[Musl]]
arch = "aarch64"
git-tree-sha1 = "8f145598de39bade4365fc38e4f2ee1190d7c2b5"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "cd224bc97ba080ba31112b21d9a6f4ae65286d982acf1619e099d2c8ca2ff9c2"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f52fa239379254f8a2fdd206fd7d7befafac04bc"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "7377f58b84b3ef7b8d3ec0a33c88c7e447cf2e75075a88cde203e1e44a66dd2e"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "caf3604462d58532b56a338d6c48ab8496bf51fe"
libc = "musl"
os = "linux"

    [[Musl.download]]
    sha256 = "ee336f55447a644c9e24af0b7b8b4fcd8125c5ab5a78c494a509173e27edc69d"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-build_log]]
arch = "x86_64"
git-tree-sha1 = "7bb8a7d5788b3edc8b4a6f760d11b45eb45b93d3"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "24922b4a93353ea02defc7c51accf6d3d83f3f984b224407b47eeb8c55c8debe"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "i686"
git-tree-sha1 = "09b2a69f378b3ec8164ed23e3fdb6e6245dbac9c"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "ba38360d9de1001b343169612d600d7357ee462838d98c63fd40fac0f629b721"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "aarch64"
git-tree-sha1 = "58bf2ff80ac2dbd11f33007e32c8bd26b66c9fc1"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "b67cf94cb1cf52a187ca00b0b015244727efe10ae4a6683a12c18fcc0eb7e966"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6602c2051e17e5383e2b2d98fc2045f92d8e63a9"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "76542d62cf16899b859154a35bd585200bd93839af176beda35f3b3c66eae8e3"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2fd529137ab0afed289c7b786d0e94d375e1673b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-build_log.download]]
    sha256 = "5410824ae773c0dd58cfb19a544bf441a2b9e62f3324adc5bb30024bf0f58813"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-build_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"

[[Musl-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4e84815bdf9208038697542f73dec5e7c90f917e"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "d0bf1eec4afb6e3b0138470bf6defa406ed48366389353915fe949d9867eec75"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-x86_64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "i686"
git-tree-sha1 = "44a8791dfd8d5997f1b83ef6cd9d886957d75b7f"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "45b86ccae8ca7a1409f48f108820458366026c79767672aeb9638b3d6e277178"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-i686-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "aarch64"
git-tree-sha1 = "c48b79a96868141ee579b7a1dc4d3ae93f02e32b"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "4e305787e98ed62ae7143a4319840c8c62c06cbe4b5718a6c3f3e9180d68b253"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-aarch64-linux-musl.tar.gz"
[[Musl-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7164c38798bf55f86c20a90a3c50cc6bdcd15040"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "f49c324fa1c5e20319dd4d2d2e5dd395d7c6d431d0b348d80e4d357a04c6526d"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-armv6l-linux-musleabihf.tar.gz"
[[Musl-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc1acbda1dd79f46488932e5e4a37b9b799a1d2d"
lazy = true
libc = "musl"
os = "linux"

    [[Musl-extract_log.download]]
    sha256 = "a9b8d6a5c4d636e2083959a063852e248e8e08dc64dcaddf7baf8f70701065c1"
    url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.25/Musl-extract_log-v1.1.25-armv7l-linux-musleabihf.tar.gz"
