name = "Musl"
version = "1.1.30"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "x86_64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3d430fbc5f7ba52d555059070c2b8dfc556fae38"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:4e74e0f836fd8bf649dbebfc63ab0e395742f92337fab8352c2db9aa5668f73b"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-build_log-v1.1.30-x86_64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:ead1bd3e5b2bef28bc39a239068e6719fa4a733d"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c0048cc832087d962312a10e487cb6a02d1bf4230c966a94581563ba488dc2f8"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-extract_log-v1.1.30-x86_64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-x86_64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:c3731bb4e6ade685344c1bf37e1fd5208fdbd1c2"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:cdfe52ae05c117ee39dbd3092ef15f0ae7020245424aa88b2e60477c90488a88"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-v1.1.30-x86_64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "i686-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:2ae9a14e9eb459b4d6ade24e5e4556869ea38d33"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:17245af5a3b03c03496dc139f09f6617a205f475ac4318899d88f9dc862d37e8"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-build_log-v1.1.30-i686-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c3e0e2832682747c1d653835e6dc1ad043b72f04"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2e9f7e681622ab7c7bea5b283cffef0ec433f4ad7030197b7d925a6429e25054"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-extract_log-v1.1.30-i686-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-i386.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:47717d0d1f9be84491c6fa61e37dcd948fddbdfb"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:0b2776220f9b3727497b6214699366e475fa82601d9ca4d6679535482087e6c8"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-v1.1.30-i686-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "aarch64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:8f811411244d392a09eb821fd18798868963d991"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:db76596be578b2005ebabecd13a733d4db0c0cbdd26629c3ff0d118a007119b3"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-build_log-v1.1.30-aarch64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c321b6f1076835885b657afc519f3f53c7a0c3bf"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e5356e3a5a4d13472df2d3cb5254b9615d79715fe118303fb41f4d2bfe9683a1"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-extract_log-v1.1.30-aarch64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-aarch64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:5a30a0cec3607b9a9ad8b79ba6caf94548d63373"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:972aa41869ed6ff2c225792e686d9b3b31a214a44cddee86aae86a1afbb842e2"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-v1.1.30-aarch64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "armv6l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3bd0b6ed2b87a73a4bbf0b2f3261d51ccddad18e"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ad56db47e26fb1a40d86da85749376d1a0ca9ecdeb201f8a182b8708bfe68968"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-build_log-v1.1.30-armv6l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:ecd43ae131a86a5e29be78af33bfc3ed59995521"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c15e389f2508bbb525fdfb7833fdad2185d4ee83e3188ab5b2e62bff7019a40b"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-extract_log-v1.1.30-armv6l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:401b70fe0e1419333ed257c556fc8d038dd16e07"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:acdbe396614a5892c018209d48ae923ea3506232cc9e62e21c7c3b5135a9d035"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-v1.1.30-armv6l-linux-musleabihf.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "armv7l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:1dd6267871ab5b760260b12065d8a65c0aa1f8ca"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:af1b239c49749abe3e187e16ee2ed7d36b91a1f58859f85d5bb19cee9790a3bc"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-build_log-v1.1.30-armv7l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4ba49fd1bd36d3cba1612851c44ca6c842093857"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e0430a14affa84406cea35d6835c1c77afd525a7364d31f29bd563adf65cd30c"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-extract_log-v1.1.30-armv7l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:272b5dfdb919133141b36aa9814663d9895f7094"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3736390703b5ec3a6b18d520c47c87856fbbdfaca0e8184e2f3317eb006395ca"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.30-GCC/Musl-v1.1.30-armv7l-linux-musleabihf.tar.gz"
