name = "Musl"
version = "1.2.8"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "x86_64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:0e56102b30b7730706f31ec8ea55c35b1695df04"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:be2141cf51a84afb149a3dc1349ddc0859d5ba86e80caed1305dc00c022876bc"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-build_log-v1.2.8-x86_64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c6233925da65596406ec1654cee8fefae0dd7a18"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:43123c4adc8f42c6e6689f5673a51010be9cdaf4e8935a99156755d196089406"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-extract_log-v1.2.8-x86_64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-.so.1"
    type = "library"
    path = "lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:136a6d4970af4575c7430ea37cfc62da514a6a7d"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:48cbd98664ee5e864b84e296372a1021f0ebeee9a093df585ceb4be651b9ddbf"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-v1.2.8-x86_64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "i686-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:4aae9dd628f84db5ba020fcc5e4332dccf8708ef"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5a7c3e61e3dcc070eb08030abf2fd285604d87fa7508f17b8662171c6ea99aac"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-build_log-v1.2.8-i686-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:21a53ad119488ad2c0dffd983d760eaf07c439a5"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e07b5e31121d788fffdd78c67d832171ab1e91adac94a4c17988386667c87891"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-extract_log-v1.2.8-i686-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-.so.1"
    type = "library"
    path = "lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:a83df83c1889bb951189165a1e8849efb59a7d62"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:61ec4925c6ec50815c13d09bb9a6399a0b0db9c7375e01a33154a6bdc926a5fe"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-v1.2.8-i686-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "aarch64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:571368caca15107137af736bd05e596aad713d63"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:9af876e259f375513baf246c25c38fc8e0bc3cffb24b93ce25e1f8bf2c43cea6"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-build_log-v1.2.8-aarch64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:63b95e9aaea313bf54b94e575730c49a37760d4b"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:7908753e7183f56b3414bd75a27ca2e230bfa2c8482f52e30f6df77553a0dc44"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-extract_log-v1.2.8-aarch64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-.so.1"
    type = "library"
    path = "lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:b780f2bb9205988fa2090ef9567eef77a321fe2c"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:eedcb0ae284b033c0ed1b14a187f23a4580abf3325f819e99fc190a3dfa96d0b"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-v1.2.8-aarch64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv6l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:84a66537af80fd5ab77756aefc5107273e7cad2d"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:48d279eaee6a4c457092bf7235de6e2b08eb3c4ed89936a4ced230ec3d402d01"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-build_log-v1.2.8-armv6l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:d7fdacd3deacee54b478ee645dab0a2376684160"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d3671d4d10bead8668c23e1cc63efc342fc7298ffc44671b05e49cd5e635fc22"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-extract_log-v1.2.8-armv6l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-.so.1"
    type = "library"
    path = "lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:142e6d933077cd4b090d26c8ccb33cab26cc46ae"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:0daab7aae33eb5c03c814ec4180c11fb0af5de1c7159e0b2e7f1e63ab557683e"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-v1.2.8-armv6l-linux-musleabihf.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv7l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:815c0a383d2953076d91242b36119a8967e67e03"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d9b526cb7550370a512f1b24d7064dcab7e5825907267d90b661843f87ddd1ff"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-build_log-v1.2.8-armv7l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b36b11923b89fc0701e8c84de53fe73820a30121"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:b8c517864a1dd1c7db98a56f6adcdfa3a11340593e9c2e4575e216fa7356ca31"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-extract_log-v1.2.8-armv7l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-.so.1"
    type = "library"
    path = "lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:64af699906228982a0ae3dcbf149af76e4af6424"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:054e85866a0503b3a6f07a61cb435159228639c896990ffeabaad0a18b249877"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.8-GCC/Musl-v1.2.8-armv7l-linux-musleabihf.tar.gz"
