name = "Musl"
version = "1.2.11"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "x86_64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:d1c75ffc7e7fa6d1553f327a8add632b0b2b8e84"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:bf27e06d9e9ad6331510f3161be2e449e79b9ed994a8c7dcf95cc80d2edd4e38"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-build_log-v1.2.11-x86_64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:153d5ca7691ef5dbe59a464e707e5cb93180284d"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d7e42b7d090edf44e8231540a505996f6ddb4e2c4db09a1c0584cc4827fd0c40"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-extract_log-v1.2.11-x86_64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-x86_64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:e66a4083e3387c5655bf354429ca0ca77bbc4904"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:37a7a69bcd639321a4a0e9b0a25d8d4191347101a8b9313d56e767e8d2782cd3"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-v1.2.11-x86_64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "i686-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f9f9939ad358aea008e5e2d355bf912193b2acb4"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:9129a682a6712fcfefd391a06bb7df4af1099dcc2dfbc5e0163a6eb69427dce8"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-build_log-v1.2.11-i686-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:dd7efa4c4f0a96c276bb39fc9ddb98d373d445ea"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:99212652728a025f212b2b67e4cf3304d3892f4b341b86d50f47d595a4672fce"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-extract_log-v1.2.11-i686-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-i386.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:e72c9c4c92dd9f77f5e07de4b1f5d9b2ff2d7fe7"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:a55c881d4455e586e70c589f8801d89befe7004ac4dc9e6b1fdcbaa5fe4563f1"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-v1.2.11-i686-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "aarch64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f76a4df61763c626c6c56ff53879b8726c57b136"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6f8ccb98ae8b6a540cd4741406c4ad9d5fcce46160554e0c986b541ada6d525e"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-build_log-v1.2.11-aarch64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4bd5e3bfc9de7a623844929fe035d7f44e713b8d"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c9ad45be0ebe07cff222ebf3ac81e23712019f96204196506c7ee8290f6e4113"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-extract_log-v1.2.11-aarch64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-aarch64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:02b299d6bb76e6f19189cfd2388e2bb5bf7cd98d"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:b61223bb3bd7cdbeeb745fd2b16400a08177b8a61fb7926d45f11ea7947d536f"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-v1.2.11-aarch64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv6l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:54863a97b866a4666ba6e677b94749d80b6d97e0"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:a9281a4156c5cc3afaad44f1713c2089047ade2051797232c7559a1537987dfd"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-build_log-v1.2.11-armv6l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:738d1fac8af0b94c691fd8de937d81a53b5e776f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:51cd0b8f7093cfe29e4b9d1adf66e746d802ba92637975d9c18f1a4e2465cca0"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-extract_log-v1.2.11-armv6l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:e1c771210cccd9635bdb82e8a69486f14b809524"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3bf0c1fb9cd3e3931deace7a927b133cc47be9dc0f08f08fc3c97100ce14eebc"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-v1.2.11-armv6l-linux-musleabihf.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv7l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:9dd5e3e5cb254a22acb2b77deedf44a0370e92f9"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:688a14362f1ed890795ac4e3cdca84c2b1b7e1b0c921afdce14f36ac9fefc597"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-build_log-v1.2.11-armv7l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:0573dfc9b4b83f89025075c0300064f8a6f855a7"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:e58886d5c9f1e7a348a20a3004f97a2b47a1db37b2c3f325892ada3368f0e4bd"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-extract_log-v1.2.11-armv7l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:579bea4e1abf8f0f610e1e6e6d6263582e9a36df"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:43da558d82598ad929dd6fd0550951cba0b59df262e95d2138903326808aa72f"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.11-GCC/Musl-v1.2.11-armv7l-linux-musleabihf.tar.gz"
