name = "Musl"
version = "1.1.29"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "x86_64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:517304a08700fb172a8a68cc23edc8ed6502edab"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ca59171b1596ee63e38b0089a4d56a3b83769dbe416e3bb4a17d64aea20a6b25"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-build_log-v1.1.29-x86_64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:49bc4f4767a22db07f87a06a74ca5b33e48b88e0"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2b57c5872b122ff321daa7e0427d187e70f14c2fd29dda4ccbc281eae0aec2c0"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-extract_log-v1.1.29-x86_64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-x86_64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:1e38050664dd15653f8460ab99915ad171ceae60"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:0119a8058105abaff04dbdaf59df4ac85f7acc59f66a14e6e4197339250b1bac"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-v1.1.29-x86_64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "i686-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f082fb2716916869a1eb60214a5b5498ce7cacd8"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b0508e68dce49442783d98ab9f9b3e0517d8eaddffad92b68bedf54349c4854f"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-build_log-v1.1.29-i686-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:d5a228e66a188782ffa25e41a8dab764b37b3168"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:32f9bca2a57b9251493373efaba01d25bc9fc5153c3d5263e5c71b185e2591ab"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-extract_log-v1.1.29-i686-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-i386.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:32d3d147874d1a378852b2b5af12c22e87473a89"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:4ccb6904d89de3fd9e5d71c6e4dfb6b91e16fe966452bbfead629ce68d8583bf"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-v1.1.29-i686-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "aarch64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:0a2b9150a3755bc8b55f12d1171dc6b689b0cc6a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:abe5657548c200826aea25ea9ac479ceb73fcfcc742659154ada344c4ab1599e"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-build_log-v1.1.29-aarch64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:381fdc9359a1e464a2ce3468566f8856cfcf5a91"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:33c7f30c260d532fd45b01595ddf279ee4c581aa0402cf65535451b33e8cfd9f"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-extract_log-v1.1.29-aarch64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-aarch64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:0758dbd4e5ea4d272644cc19756cd8fb1b15a115"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d13dc42deb04639920135c835a8ce1ad947f2da8ce7b1ed0ec7a799ad9febb53"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-v1.1.29-aarch64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "armv6l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:1be74eb95e43f2f8d13ace7d7940c68ee0fada87"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:102e2ea441a1b44e25c0b4bfcc9e122f28332fd9f940fc76d7ee032a3b84ea23"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-build_log-v1.1.29-armv6l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:09a36bf0721780d44c3fc9a834a863a658226a3e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:ab4e26c422d9a27465a8530be1e743554d917c54e22ff4c7737939d14c4465b9"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-extract_log-v1.1.29-armv6l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:941b8cd08a639f9491133c43329a44b33550a008"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1033f7296b5ff983f8e6ed1235518b174a5173932eaeabed60eee5714e429b19"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-v1.1.29-armv6l-linux-musleabihf.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.1.24"
platform = "armv7l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:2dd67c677b5d4db609aca819463e5cb89f400758"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:1648018a229ef0dae1dc75bfa189ad05815b765cfdaeb4c8d238c9cc61864857"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-build_log-v1.1.29-armv7l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:155d53991f44d339cf6827db45b9994e2aac9c59"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:33c4830bd6a807eb3c04cde6dca0355fa2b3e67c0ca6aef5978606033e187b50"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-extract_log-v1.1.29-armv7l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:0d04173adea3b201b8ec3b955894c487de4c5853"
    url = "https://musl.libc.org/releases/musl-1.1.24.tar.gz"

    [builds.artifact]
    treehash = "sha1:4c9b0b9a7dca4d80e16884a42c9aa5495a1aa2d6"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3e11c26d692c16564db53e7dbfa5843fbf148a8b82e5beb9f0de86f5a0b80b9f"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.1.29-GCC/Musl-v1.1.29-armv7l-linux-musleabihf.tar.gz"
