name = "Musl"
version = "1.2.9"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "x86_64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:914087b6d722f013fdcdcb2253b02d89193d9f27"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d3db729f3e3e12f227bde027f2c145c38ac3953fed3ba8c149e8ccaa4fbc46c8"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-build_log-v1.2.9-x86_64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:31cbda08ef60fc701bf0145ae38232c6032eec6c"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:16a0ff18838e993dd47f8516ade5d3359cb4ff16a914f279fc1440a5ce6a36d2"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-extract_log-v1.2.9-x86_64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-x86_64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:51c35712cd314c2d1ea4782701a1b2ca98f76a09"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:4dcc7272be78e99a3be045e6ab140d244b6061e6daec53918cb2d005b56abbef"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-v1.2.9-x86_64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "i686-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f786290f10a6b77f175d50c0618480891f31e388"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:08f5295efafdf6242048d4bfbca410c74d3918d6486f9b2b3365fc7519c97e95"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-build_log-v1.2.9-i686-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b74a160e65cbf4e3c166c36ed2f698747ffda32f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c9fab0dca07fa8415b1891ae71fd247138101f144f1994b94cd7bf30da98b585"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-extract_log-v1.2.9-i686-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-i386.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:7a9fe6d2bf18f391e6dc104f32b39f2424aa13d5"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5c44d1ec9ca55e287964adcb2a2f83fe5e32e605932c2a6e8886629a66787e6d"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-v1.2.9-i686-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "aarch64-linux-musl"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:98b3f42272a358c0ba351f475d1211f730549596"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ead3df6b5c1cdc29d825a023e0b363ee1e25e8384eed58eee9a2749c569c33af"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-build_log-v1.2.9-aarch64-linux-musl.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:75cbc548eea6a9d2cbfa8da3c50f121ec088d20f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:816b7e59f57c8c3697757030b855aef603936785bea1540a262ac8ac4aedf985"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-extract_log-v1.2.9-aarch64-linux-musl.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-aarch64.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:914a719a60788d7106cbb2401ca0be845695f8c7"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:05cb8ee24f726ede4d15f3faf493e005bff5a46801fb5838ecebbe2f49c50c9e"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-v1.2.9-aarch64-linux-musl.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv6l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:7db007218c8708904581b15a28795be24d346223"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b52c09bc54923af603b28b27670eff7ec56e9260a27939badd1b54029ccc2422"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-build_log-v1.2.9-armv6l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b0eaf71071ca8abcfbf423eae50c01803efc8146"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:9e0db8f16e39456454b1feb64a966569cd9cd2232adb2c55275196567606872a"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-extract_log-v1.2.9-armv6l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:7a35854a85ad68a6712d7581ad4945e344d6912a"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:0e252756a83a199ac8f55a43a38550d174f9f3e6e1c42b3b30f05faedc4eb21c"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-v1.2.9-armv6l-linux-musleabihf.tar.gz"
[[builds]]
deps = []
name = "Musl"
lazy = "false"
src_version = "1.2.5"
platform = "armv7l-linux-musleabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:d24e9feb5e4506d793971ef5c7bfa4acdd009d96"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d10d7310a9f54ba7d28ddca1be4c60185d2c783c349942a73962e03cd1a5cacc"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-build_log-v1.2.9-armv7l-linux-musleabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:0952548649d3636ddd21f471bcf4f9d904952e10"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4fb46e92cd65ad8b662ea1f0fb07074b2541318a4c597a4223de76cdea81fdd4"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-extract_log-v1.2.9-armv7l-linux-musleabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.musl-armhf.so.1"
    type = "library"
    path = "usr/lib/libc.so"

    [[builds.sources]]
    treehash = "sha1:772272a3f819d22b9eac7888c8d5134af5449977"
    url = "https://musl.libc.org/releases/musl-1.2.5.tar.gz"

    [builds.artifact]
    treehash = "sha1:684efb2f6bfb70199f261d73afbc709aed6fdfe4"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5bef96005ccf8cb48893f76b816e708e807f78c62b57816440a81dd734336156"
        url = "https://github.com/staticfloat/Musl_jll.jl/releases/download/v1.2.9-GCC/Musl-v1.2.9-armv7l-linux-musleabihf.tar.gz"
